### PR TITLE
Update sass-lint version

### PR DESCRIPTION
**Pull request by Gaurav0**

### CODE REVIEW

**Comment by artursmirnov** [comment]
@Gaurav0 thanks!

**Comment by artursmirnov** [comment]
Published as `2.1.1`

**Comment by Gaurav0** [comment]
@artursmirnov Not getting upgraded. Can you please publish as 3.1.0 ?

**Comment by artursmirnov** [comment]
Done, published as `3.1.0` https://www.npmjs.com/package/broccoli-scss-linter

**Pull request merged**
